# Submodule stub for curl_cffi.aiohttp (used in transport/curl_cffi_runtime.py).

from typing import Any
from collections.abc import AsyncIterator

class AsyncSession:
    def __init__(
        self,
        *,
        impersonate: str | None = None,
        proxy: str | None = None,
        timeout: float = 30.0,
        headers: dict[str, str] | None = None,
        **kwargs: Any,
    ) -> None: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...
    async def head(self, url: str, **kwargs: Any) -> Response: ...
    async def put(self, url: str, **kwargs: Any) -> Response: ...
    async def delete(self, url: str, **kwargs: Any) -> Response: ...
    async def request(self, method: str, url: str, **kwargs: Any) -> Response: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(self, *args: Any) -> None: ...

class Response:
    status_code: int
    status: int  # alias for httpx-compatible access
    headers: dict[str, str]
    text: str
    content: bytes
    url: str
    encoding: str | None
    cookies: dict[str, str]
    history: list[Response]
    extensions: dict[str, Any]  # e.g. {"http_version": b"1.1"}
    request: Any  # httpx compatible
    def __init__(self, *, status_code: int, headers: dict, content: bytes, **kwargs: Any) -> None: ...
    def json(self, **kwargs: Any) -> Any: ...
    def raise_for_status(self) -> None: ...
    def iter_content(self, chunk_size: int = 1024) -> Any: ...
    def iter_lines(self, chunk_size: int = 1024) -> Any: ...
    def aiter_content(self, chunk_size: int = 1024) -> Any: ...
    def aiter_lines(self, chunk_size: int = 1024) -> Any: ...
    async def aiter_chunked(self, chunk_size: int = 65536) -> AsyncIterator[bytes]: ...
    # --- httpx-compatible accessors for curl_cffi Response ---
    @property
    def http_version(self) -> str | None: ...

class AsyncClient(AsyncSession):
    pass
