# curl_cffi.requests sub-stub (sync, used elsewhere)
from typing import Any

class Session:
    def __init__(self, *, impersonate: str | None = None, **kwargs: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...
    def request(self, method: str, url: str, **kwargs: Any) -> Response: ...
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, *args: Any) -> None: ...

class Response:
    status_code: int
    headers: dict[str, str]
    text: str
    content: bytes
    url: str
    encoding: str | None
    def __init__(self, *, status_code: int, headers: dict, content: bytes, **kwargs: Any) -> None: ...
    def json(self, **kwargs: Any) -> Any: ...
    def raise_for_status(self) -> None: ...
    def iter_content(self, chunk_size: int = 1024) -> Any: ...
    def iter_lines(self, chunk_size: int = 1024) -> Any: ...
