# Stub for wasmtime (PyPI: wasmtime) — used in tools/wasm_sandbox.py
# v45+ API surface (constructor signatures matched to .venv inspection).

from typing import Any, Iterable, Sequence

class WasmtimeError(Exception): ...
class ExitTrap(Exception):
    code: int

# Configuration
class Config:
    def __init__(self) -> None: ...
    def debug_info(self, enable: bool) -> Config: ...
    def consume_fuel(self, enable: bool) -> Config: ...
    def epoch_interruption(self, enable: bool) -> Config: ...
    def wasm_multi_memory(self, enable: bool) -> Config: ...
    def wasm_module_linking(self, enable: bool) -> Config: ...
    def cache_config_load_default(self, path: str) -> Config: ...
    def tail_call(self, enable: bool) -> Config: ...
    def target(self, target: str) -> Config: ...
    def strategy(self, strategy: str) -> Config: ...
    def CraneliftOptLevel(self, level: int) -> Config: ...
    def parallel_compilation(self, enable: bool) -> Config: ...

class Engine:
    def __init__(self, config: Config | None = None) -> None: ...
    def close(self) -> None: ...
    def increment_epoch(self) -> None: ...
    def is_pulley(self) -> bool: ...
    @property
    def ptr(self) -> int: ...

class Store:
    def __init__(
        self,
        engine: Engine,
        data: Any = None,
        limiter: Any = None,
        fuel: int | None = None,
    ) -> None: ...
    # v45 API
    def set_fuel(self, fuel: int) -> None: ...
    def get_fuel(self) -> int: ...
    def set_epoch_deadline(self, ticks_after_current: int) -> None: ...
    def set_limits(self, limits: Any) -> None: ...
    def set_wasi(self, wasi: WasiConfig) -> None: ...
    def data(self) -> Any: ...
    def gc(self) -> None: ...
    def close(self) -> None: ...

class WasiConfig:
    def __init__(self) -> None: ...
    def inherit_stderr(self) -> WasiConfig: ...
    def inherit_stdout(self) -> WasiConfig: ...
    def inherit_stdin(self) -> WasiConfig: ...
    def preopen_dir(self, dir: str, guest_path: str) -> WasiConfig: ...
    def map_dir(self, host_path: str, guest_path: str) -> WasiConfig: ...
    def env(self, vars: list[tuple[str, str]]) -> WasiConfig: ...
    def arg(self, args: list[str]) -> WasiConfig: ...

class Module:
    def __init__(self, engine: Engine, wasm: str | bytes) -> None: ...
    @classmethod
    def deserialize(cls, engine: Engine, data: bytes) -> Module: ...
    @classmethod
    def deserialize_from_file(cls, engine: Engine, path: str) -> Module: ...
    def serialize(self) -> bytes: ...
    def exports(self) -> list[ExportType]: ...
    def imports(self) -> list[ImportType]: ...

class Instance:
    """v45 API: Instance(store, module, imports) — not (module, imports)."""
    def __init__(
        self,
        store: Store,
        module: Module,
        imports: Sequence[Func | Table | Memory | SharedMemory | Global | Tag] = ...,
    ) -> None: ...
    def exports(self, store: Store) -> InstanceExports: ...
    @classmethod
    def pre_instantiate(cls, module: Module) -> InstancePre: ...

class InstancePre:
    def instantiate(self, store: Store) -> Instance: ...

class InstanceExports:
    def __getitem__(self, name: str) -> Extern: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterable[Extern]: ...

class Extern:
    pass

class Func(Extern):
    type: FuncType
    def __call__(self, *args: Any) -> Any: ...
    def call(self, store: Store, *args: Any) -> Any: ...
    def drop(self, store: Store) -> None: ...

class FuncType:
    params: list[ValType]
    results: list[ValType]

class Table(Extern):
    def __init__(self, store: Store, ty: TableType, init: Any) -> None: ...
    def read(self, store: Store, idx: int) -> Any: ...
    def write(self, store: Store, idx: int, val: Any) -> None: ...
    def size(self, store: Store) -> int: ...

class TableType:
    def __init__(self, element: ValType, limits: Limits) -> None: ...

class Memory(Extern):
    def __init__(self, store: Store, ty: MemoryType) -> None: ...
    def read(self, store: Store, offset: int, length: int) -> bytes: ...
    def write(self, store: Store, offset: int, data: bytes) -> None: ...
    def size(self, store: Store) -> int: ...
    def grow(self, store: Store, delta: int) -> int: ...
    def data_len(self, store: Store) -> int: ...
    def data(self, store: Store) -> bytearray: ...

class SharedMemory(Memory): ...
class MemoryType: ...
class Global(Extern): ...
class GlobalType: ...
class Tag(Extern): ...
class TagType: ...

class Limits:
    def __init__(self, min: int, max: int | None = None) -> None: ...

class ValType:
    i32: ValType
    i64: ValType
    f32: ValType
    f64: ValType
    v128: ValType
    funcref: ValType
    externref: ValType

class Val:
    @classmethod
    def i32(cls, v: int) -> Val: ...
    @classmethod
    def i64(cls, v: int) -> Val: ...
    @classmethod
    def f32(cls, v: float) -> Val: ...
    @classmethod
    def f64(cls, v: float) -> Val: ...
    value: Any

class Linker:
    def __init__(self, engine: Engine) -> None: ...
    def define_func(self, module: str, name: str, func: Func) -> None: ...
    def define_wasi(self, wasi: WasiConfig) -> None: ...
    def instantiate(self, store: Store, module: Module) -> Instance: ...
    def get(self, store: Store, name: str) -> Func | None: ...
    def get_default(self, store: Store, name: str) -> Func | None: ...

class ExportType:
    name: str
    type: Any

class ImportType:
    name: str
    type: Any
    module: str

class Trap(Exception):
    pass

class Frame:
    func_name: str
    module_name: str
    func_index: int
    module_offset: int

class DirPerms:
    READ: int
    WRITE: int
    EXECUTE: int

class FilePerms:
    READ: int
    WRITE: int
    EXECUTE: int

# Helper functions
def wat2wasm(source: str) -> bytes: ...
