# Stub for Foundation (pyobjc-framework-Foundation; Darwin-only)
# Minimal surface — only what hledac lazy-imports.

class NSObject:
    pass

class NSData(NSObject):
    @classmethod
    def dataWithBytes_length_(cls, bytes: bytes, length: int) -> NSData: ...
    def bytes(self) -> bytes: ...
    def length(self) -> int: ...

class NSString(NSObject):
    @classmethod
    def stringWithString_(cls, s: str) -> NSString: ...
    def stringByAppendingString_(self, s: NSString) -> NSString: ...
    @classmethod
    def stringWithCString_encoding_(cls, cstr: bytes, encoding: int) -> NSString: ...

class NSNumber(NSObject):
    @classmethod
    def numberWithInt_(cls, n: int) -> NSNumber: ...
    @classmethod
    def numberWithFloat_(cls, n: float) -> NSNumber: ...
    @classmethod
    def numberWithBool_(cls, b: bool) -> NSNumber: ...
    def intValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def boolValue(self) -> bool: ...
    def doubleValue(self) -> float: ...

class NSArray(NSObject):
    @classmethod
    def arrayWithArray_(cls, items: list) -> NSArray: ...
    @classmethod
    def arrayWithObject_(cls, item: object) -> NSArray: ...
    def count(self) -> int: ...
    def objectAtIndex_(self, idx: int) -> object: ...

class NSURL(NSObject):
    @classmethod
    def URLWithString_(cls, s: str) -> NSURL: ...
    @classmethod
    def fileURLWithPath_(cls, path: str) -> NSURL: ...

class NSError(NSObject):
    code: int
    domain: str
    userInfo: dict

class NSDictionary(NSObject):
    @classmethod
    def dictionaryWithDictionary_(cls, d: dict) -> NSDictionary: ...
    def objectForKey_(self, key: str) -> object: ...

# Constants commonly referenced
NSUTF8StringEncoding: int
NSASCIIStringEncoding: int
