# Stub for oqs (liboqs-python) — post-quantum crypto
# Real API surface derived from .venv inspection; covers hledac/security usage.

OQS_VERSION: str
OQS_SUCCESS: int
oqs_version: str
oqs_python_version: str

class MechanismNotEnabledError(Exception): ...
class MechanismNotSupportedError(Exception): ...
class InvalidKeyLength(Exception): ...
class DuplicateNameException(Exception): ...
class KeyMismatchException(Exception): ...

# Module-level functions
def get_enabled_kem_mechanisms() -> list[str]: ...
def get_enabled_sig_mechanisms() -> list[str]: ...
def get_enabled_stateful_sig_mechanisms() -> list[str]: ...
def get_supported_kem_mechanisms() -> list[str]: ...
def get_supported_sig_mechanisms() -> list[str]: ...
def get_supported_stateful_sig_mechanisms() -> list[str]: ...
def is_kem_enabled(name: str) -> bool: ...
def is_sig_enabled(name: str) -> bool: ...
def sig_supports_context(name: str) -> bool: ...

class Signature:
    """Post-quantum signature (or stateful via StatefulSignature)."""
    def __init__(self, alg_name: str, secret_key: bytes | None = None) -> None: ...
    def generate_keypair(self) -> bytes: ...
    def sign(self, message: bytes) -> bytes: ...
    def verify(self, message: bytes, signature: bytes, public_key: bytes) -> bool: ...
    def export_secret_key(self) -> bytes: ...
    def export_public_key(self) -> bytes: ...
    def import_secret_key(self, key: bytes) -> None: ...
    def import_public_key(self, key: bytes) -> None: ...
    def free(self) -> None: ...
    def sign_with_ctx_str(self, message: bytes, context: str) -> bytes: ...
    def verify_with_ctx_str(self, message: bytes, signature: bytes, public_key: bytes, context: str) -> bool: ...
    @property
    def alg_version(self) -> str: ...
    @property
    def claimed_nist_level(self) -> int: ...
    @property
    def euf_cma(self) -> bool: ...
    @property
    def suf_cma(self) -> bool: ...
    @property
    def length_public_key(self) -> int: ...
    @property
    def length_secret_key(self) -> int: ...
    @property
    def length_signature(self) -> int: ...
    @property
    def method_name(self) -> str: ...
    @property
    def sig_with_ctx_support(self) -> bool: ...

class StatefulSignature(Signature): ...

class KeyEncapsulation:
    """Post-quantum KEM."""
    def __init__(self, alg_name: str, secret_key: bytes | None = None) -> None: ...
    def generate_keypair(self) -> bytes: ...
    def generate_keypair_seed(self, seed: bytes) -> bytes: ...
    def encap_secret(self, public_key: bytes) -> bytes: ...
    def decap_secret(self, ciphertext: bytes) -> bytes: ...
    def encapsulate(self, public_key: bytes) -> bytes: ...
    def decapsulate(self, ciphertext: bytes) -> bytes: ...
    def export_secret_key(self) -> bytes: ...
    def export_public_key(self) -> bytes: ...
    def export_shared_secret(self) -> bytes: ...
    def free(self) -> None: ...
    @property
    def alg_version(self) -> str: ...
    @property
    def claimed_nist_level(self) -> int: ...
    @property
    def ind_cca(self) -> bool: ...
    @property
    def length_ciphertext(self) -> int: ...
    @property
    def length_keypair_seed(self) -> int: ...
    @property
    def length_public_key(self) -> int: ...
    @property
    def length_secret_key(self) -> int: ...
    @property
    def length_shared_secret(self) -> int: ...
    @property
    def method_name(self) -> str: ...
