"""
P4-2: IOC Co-occurrence Speculative Prefetch
============================================

Problem: System predicts next investigation pivots reactively (from known findings),
         but has no model for "IOCs that frequently co-occur in same finding."
Solution: Mine co-occurrence patterns from accumulated findings in real-time,
          generate speculative IOC connections for prefetch.

Architecture:
    Accumulated findings in DuckDB (per sprint)
            │
            ▼
    CoOccurrenceMiner.analyze(findings)
            │
            ├─► Co-occurrence matrix: (IOC_A, IOC_B) → count
            │
            ├─► Top pairs by confidence (support × confidence)
            │
            └─► SpeculativeEdge suggestions
                        │
                        ▼
            SpeculativePrefetcherQueue
            (fires prefetch tasks for likely next IOCs)
                        │
                        ├─► domain → related domains (same finding)
                        ├─► IP → related IPs (same subnet in findings)
                        ├─► hash → related hashes (same file IOC)
                        └─► email → related domains (registrant correlation)

M1 8GB constraints:
- In-memory co-occurrence matrix bounded: _MAX_PAIRS=10000
- LRU eviction by support count
- Computation runs in background, does not block acquisition
- Results stored in DuckDB for cross-sprint persistence
"""
from __future__ import annotations

import asyncio
import logging
import re
import sqlite3
import time
from collections import defaultdict
from itertools import combinations
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from knowledge.duckdb_store import CanonicalFinding

from hledac.universal.utils.async_helpers import safe_gather_dropin

logger = logging.getLogger(__name__)

# Bounded co-occurrence matrix
_MAX_PAIRS: int = 10_000  # max (IOC_A, IOC_B) pairs in memory
_MAX_IOC_TYPES: int = 6  # domain, ip, url, hash, email, uri
_MIN_SUPPORT: int = 2  # minimum co-occurrence count to be considered
_MIN_CONFIDENCE: float = 0.3  # minimum confidence ratio


@dataclass
class CoOccurrencePair:
    """A co-occurrence relationship between two IOCs."""
    ioc_a: str
    ioc_b: str
    ioc_type_a: str
    ioc_type_b: str
    support: int = 1  # how many times co-occurred
    confidence_a_to_b: float = 0.0  # P(B|A)
    confidence_b_to_a: float = 0.0  # P(A|B)
    last_seen: float = 0.0
    score: float = 0.0  # combined metric for ranking


@dataclass
class SpeculativeEdge:
    """
    A speculative IOC connection for prefetch.

    Generated by co-occurrence analysis.
    """
    source_ioc: str
    source_type: str
    target_ioc: str
    target_type: str
    confidence: float
    reason: str  # e.g., "co-occurred in 5 findings", "same AS number"
    prefetch_priority: int  # 0=highest, higher=lower
    speculative: bool = True  # True = speculative, False = confirmed


@dataclass
class IOCounterStats:
    """Statistics for IOC co-occurrence mining."""
    findings_analyzed: int = 0
    pairs_mined: int = 0
    speculative_edges: int = 0
    prefetch_tasks_dispatched: int = 0
    compute_time_ms: float = 0.0


class IOCooccurrenceMiner:
    """
    Mines co-occurrence patterns from CanonicalFinding objects.

    Generates SpeculativeEdge recommendations for prefetch.

    Algorithm:
    1. Extract IOC entities from finding payload (domains, IPs, URLs, hashes)
    2. For each finding, increment co-occurrence count for all IOC pairs
    3. Compute confidence metrics (conditional probabilities)
    4. Rank pairs by support × confidence
    5. Generate SpeculativeEdges for top pairs
    """

    def __init__(self, lmdb_path: Path | None = None) -> None:
        # In-memory co-occurrence matrix
        self._pairs: dict[tuple[str, str], CoOccurrencePair] = {}
        # Per-IOC occurrence count for confidence computation
        self._ioc_counts: dict[str, int] = defaultdict(int)
        # Per-IOC type counter
        self._type_counts: dict[str, int] = defaultdict(int)
        # Lock for thread-safety
        self._lock = asyncio.Lock()
        self._stats = IOCounterStats()
        self._lmdb_path = lmdb_path

    # ─── IOC Extraction ─────────────────────────────────────────────────────────

    @staticmethod
    def extract_iocs_from_finding(finding: CanonicalFinding) -> list[tuple[str, str]]:
        """
        Extract (ioc_value, ioc_type) pairs from a CanonicalFinding.

        Types: domain, ip, url, hash, email, uri, asn, cidr, file
        """
        iocs: list[tuple[str, str]] = []
        payload = finding.payload_text or ""

        # Domain extraction
        domain_pattern = re.compile(
            r'\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}\b'
        )
        for m in domain_pattern.finditer(payload):
            val = m.group().lower()
            if len(val) > 3:  # Filter noise
                iocs.append((val, "domain"))

        # IP extraction
        ip_pattern = re.compile(
            r'\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}'
            r'(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b'
        )
        for m in ip_pattern.finditer(payload):
            iocs.append((m.group(), "ip"))

        # URL extraction
        url_pattern = re.compile(r'https?://[^\s<>"{}|\\^`\[\]]+')
        for m in url_pattern.finditer(payload):
            val = m.group().lower()
            if len(val) > 8:
                iocs.append((val, "url"))

        # Hash extraction (MD5, SHA1, SHA256)
        hash_pattern = re.compile(
            r'\b(?:[a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64})\b'
        )
        for m in hash_pattern.finditer(payload):
            iocs.append((m.group().lower(), "hash"))

        # Email extraction
        email_pattern = re.compile(r'\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b')
        for m in email_pattern.finditer(payload):
            iocs.append((m.group().lower(), "email"))

        return iocs

    # ─── Co-occurrence Mining ────────────────────────────────────────────────────

    async def analyze(self, findings: list[CanonicalFinding]) -> list[SpeculativeEdge]:
        """
        Analyze findings and return speculative IOC edges.

        Runs co-occurrence mining in background thread.
        """
        t0 = time.monotonic()
        loop = asyncio.get_running_loop()

        edges = await loop.run_in_executor(None, self._analyze_sync, findings)

        self._stats.compute_time_ms = (time.monotonic() - t0) * 1000
        return edges

    def _analyze_sync(self, findings: list[CanonicalFinding]) -> list[SpeculativeEdge]:
        """Synchronous co-occurrence mining."""
        # Track (ioc_a, ioc_b) -> support increment per finding
        # Each finding contributes at most 1 to a pair's support
        pair_support: dict[tuple[str, str], int] = defaultdict(int)

        for finding in findings:
            iocs = self.extract_iocs_from_finding(finding)
            if len(iocs) < 2:
                continue

            # Deduplicate within finding
            unique_iocs = list(dict.fromkeys(iocs))

            # Increment type counts
            for val, ioc_type in unique_iocs:
                self._ioc_counts[val] += 1
                self._type_counts[ioc_type] += 1

            # Generate all pairs (ordered to avoid duplicate (A,B) vs (B,A))
            for (i, (val_a, type_a)), (j, (val_b, type_b)) in combinations(enumerate(unique_iocs), 2):

                    if val_a == val_b:
                        continue

                    # Normalize key (smaller IOC first for consistent lookup)
                    if val_a > val_b:
                        val_a, val_b = val_b, val_a
                        type_a, type_b = type_b, type_a

                    key = (val_a, val_b)
                    pair_support[key] += 1

        # Build CoOccurrencePairs from per-finding support counts
        for key, support in pair_support.items():
            val_a, val_b = key
            # Determine types from stored type info
            type_a = "domain"
            type_b = "domain"
            # Look up existing pair to get types
            existing = self._pairs.get(key)
            if existing:
                type_a = existing.ioc_type_a
                type_b = existing.ioc_type_b

            if existing:
                existing.support += support
                existing.last_seen = time.time()
            else:
                if len(self._pairs) >= _MAX_PAIRS:
                    self._evict_lru()
                pair = CoOccurrencePair(
                    ioc_a=val_a, ioc_b=val_b,
                    ioc_type_a=type_a, ioc_type_b=type_b,
                    support=support,
                    last_seen=time.time(),
                )
                self._pairs[key] = pair

        self._stats.findings_analyzed += len(findings)
        self._stats.pairs_mined = len(self._pairs)

        # Compute confidence metrics and generate edges
        edges = self._generate_edges()

        return edges

    def _generate_edges(self) -> list[SpeculativeEdge]:
        """Generate SpeculativeEdge recommendations from co-occurrence pairs."""
        edges: list[SpeculativeEdge] = []
        now = time.time()

        for pair in self._pairs.values():
            if pair.support < _MIN_SUPPORT:
                continue

            # Compute confidence: P(B|A) = support(A,B) / support(A)
            count_a = self._ioc_counts.get(pair.ioc_a, 1)
            count_b = self._ioc_counts.get(pair.ioc_b, 1)

            pair.confidence_a_to_b = pair.support / count_a
            pair.confidence_b_to_a = pair.support / count_b

            if pair.confidence_a_to_b < _MIN_CONFIDENCE and pair.confidence_b_to_a < _MIN_CONFIDENCE:
                continue

            # Score = support × max(confidence_A_to_B, confidence_B_to_A)
            pair.score = pair.support * max(pair.confidence_a_to_b, pair.confidence_b_to_a)

            # Generate edges in both directions
            if pair.confidence_a_to_b >= _MIN_CONFIDENCE:
                edges.append(SpeculativeEdge(
                    source_ioc=pair.ioc_a,
                    source_type=pair.ioc_type_a,
                    target_ioc=pair.ioc_b,
                    target_type=pair.ioc_type_b,
                    confidence=pair.confidence_a_to_b,
                    reason=f"co-occurred in {pair.support} findings",
                    prefetch_priority=max(0, 100 - int(pair.score)),
                    speculative=True,
                ))

            if pair.confidence_b_to_a >= _MIN_CONFIDENCE:
                edges.append(SpeculativeEdge(
                    source_ioc=pair.ioc_b,
                    source_type=pair.ioc_type_b,
                    target_ioc=pair.ioc_a,
                    target_type=pair.ioc_type_a,
                    confidence=pair.confidence_b_to_a,
                    reason=f"co-occurred in {pair.support} findings",
                    prefetch_priority=max(0, 100 - int(pair.score)),
                    speculative=True,
                ))

        # Sort by score and limit
        edges.sort(key=lambda e: (e.prefetch_priority, -e.confidence))
        edges = edges[:500]  # Top 500 speculative edges

        self._stats.speculative_edges = len(edges)
        return edges

    def _evict_lru(self) -> None:
        """Evict lowest-support pair to make room for new one."""
        if not self._pairs:
            return

        # Evict lowest support pairs first (keep high-support ones)
        sorted_pairs = sorted(self._pairs.items(), key=lambda x: x[1].support)
        evict_count = max(1, len(self._pairs) // 10)  # Evict 10%

        for key, _ in sorted_pairs[:evict_count]:
            del self._pairs[key]

    # ─── Persistence ───────────────────────────────────────────────────────────

    async def persist(self, db_path: Path) -> None:
        """
        Persist co-occurrence matrix to SQLite for cross-sprint recall.

        Called at end of sprint.
        """
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, self._persist_sync, db_path)

    def _persist_sync(self, db_path: Path) -> None:
        """Synchronous persistence to SQLite."""
        db_path.parent.mkdir(parents=True, exist_ok=True)

        conn = sqlite3.connect(str(db_path))
        conn.execute(
            "CREATE TABLE IF NOT EXISTS ioc_cooccurrence "
            "(ioc_a TEXT, ioc_b TEXT, ioc_type_a TEXT, ioc_type_b TEXT, "
            "support INTEGER, confidence REAL, score REAL, last_seen REAL)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_score ON ioc_cooccurrence(score DESC)"
        )
        conn.execute("DELETE FROM ioc_cooccurrence")

        for pair in self._pairs.values():
            if pair.support >= _MIN_SUPPORT:
                conn.execute(
                    "INSERT INTO ioc_cooccurrence VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (
                        pair.ioc_a, pair.ioc_b, pair.ioc_type_a, pair.ioc_type_b,
                        pair.support,
                        max(pair.confidence_a_to_b, pair.confidence_b_to_a),
                        pair.score, pair.last_seen,
                    )
                )

        conn.commit()
        conn.close()

    async def load(self, db_path: Path) -> None:
        """Load co-occurrence matrix from SQLite at sprint start."""
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, self._load_sync, db_path)

    def _load_sync(self, db_path: Path) -> None:
        """Synchronous load from SQLite."""
        if not db_path.exists():
            return

        conn = sqlite3.connect(str(db_path))
        rows = conn.execute(
            "SELECT ioc_a, ioc_b, ioc_type_a, ioc_type_b, support, "
            "confidence, score, last_seen FROM ioc_cooccurrence "
            "ORDER BY score DESC LIMIT ?", (_MAX_PAIRS,)
        ).fetchall()
        conn.close()

        self._pairs.clear()
        for row in rows:
            pair = CoOccurrencePair(
                ioc_a=row[0], ioc_b=row[1],
                ioc_type_a=row[2], ioc_type_b=row[3],
                support=row[4],
                confidence_a_to_b=row[5], confidence_b_to_a=row[5],
                score=row[6], last_seen=row[7],
            )
            self._pairs[(row[0], row[1])] = pair

    # ─── Speculative Prefetch ──────────────────────────────────────────────────

    async def get_speculative_edges_for_ioc(
        self, ioc_value: str, limit: int = 5
    ) -> list[SpeculativeEdge]:
        """
        Get top speculative edges originating from a specific IOC.

        Used by speculative prefetcher to know which IOCs to fetch next.
        """
        edges: list[SpeculativeEdge] = []
        async with self._lock:
            for pair in self._pairs.values():
                if pair.ioc_a == ioc_value and pair.support >= _MIN_SUPPORT:
                    edges.append(SpeculativeEdge(
                        source_ioc=pair.ioc_a,
                        source_type=pair.ioc_type_a,
                        target_ioc=pair.ioc_b,
                        target_type=pair.ioc_type_b,
                        confidence=pair.confidence_a_to_b,
                        reason=f"co-occurred in {pair.support} findings",
                        prefetch_priority=max(0, 100 - int(pair.score)),
                        speculative=True,
                    ))
                elif pair.ioc_b == ioc_value and pair.support >= _MIN_SUPPORT:
                    edges.append(SpeculativeEdge(
                        source_ioc=pair.ioc_b,
                        source_type=pair.ioc_type_b,
                        target_ioc=pair.ioc_a,
                        target_type=pair.ioc_type_a,
                        confidence=pair.confidence_b_to_a,
                        reason=f"co-occurred in {pair.support} findings",
                        prefetch_priority=max(0, 100 - int(pair.score)),
                        speculative=True,
                    ))

        edges.sort(key=lambda e: (e.prefetch_priority, -e.confidence))
        return edges[:limit]

    def get_stats(self) -> IOCounterStats:
        """Return mining statistics."""
        return self._stats


# ─── SpeculativePrefetcher ─────────────────────────────────────────────────────


@dataclass
class PrefetcherStats:
    """Statistics for the speculative prefetcher."""
    edges_received: int = 0
    prefetch_dispatched: int = 0
    prefetch_completed: int = 0
    prefetch_failed: int = 0


class SpeculativePrefetcher:
    """
    Takes SpeculativeEdges from IOCooccurrenceMiner and fires prefetch tasks.

    Architecture:
        IOCooccurrenceMiner.generate() → SpeculativeEdge[]
                │
                ▼
        SpeculativePrefetcher.dispatch_batch(edges)
                │
                ├─► validate edge (not stale, not already fetched)
                ├─► build fetch task (URL/IP/DNS based on IOC type)
                └─► submit to FetchCoordinator or NonfeedCandidateLedger

    M1 8GB: Batched dispatch (max 10 concurrent prefetches),
            bounded queue for pending prefetches.
    """

    def __init__(
        self,
        fetch_coordinator: Any = None,  # FetchCoordinator
        candidate_ledger: Any = None,  # NonfeedCandidateLedger
    ) -> None:
        self._fetch_coordinator = fetch_coordinator
        self._candidate_ledger = candidate_ledger
        self._seen_edges: set[tuple[str, str]] = set()  # (source, target) dedup
        self._seen_lock = asyncio.Lock()
        self._stats = PrefetcherStats()
        self._prefetch_queue: asyncio.Queue[Any] = asyncio.Queue(
            maxsize=100
        )
        self._workers: list[asyncio.Task[None]] = []
        self._running = False

    async def start(self, num_workers: int = 3) -> None:
        """Start prefetcher workers."""
        if self._running:
            return
        self._running = True

        for i in range(num_workers):
            task = asyncio.create_task(self._prefetch_worker(worker_id=i))
            self._workers.append(task)

        logger.info(f"SpeculativePrefetcher: started {num_workers} workers")

    async def stop(self, timeout: float = 10.0) -> None:
        """Stop prefetcher workers gracefully."""
        if not self._running:
            return
        self._running = False

        # Send poison
        for _ in self._workers:
            try:
                self._prefetch_queue.put_nowait((None, None))
            except asyncio.QueueFull:
                pass

        try:
            await asyncio.wait_for(
                safe_gather_dropin(*self._workers, label="ioc_cooccurrence_miner:prefetcher"),
                timeout=timeout,
            )
        except TimeoutError:
            logger.warning("SpeculativePrefetcher: shutdown timeout")

        self._workers.clear()

    async def dispatch_batch(
        self, edges: list[SpeculativeEdge]
    ) -> int:
        """
        Dispatch a batch of speculative edges for prefetching.

        Returns number of prefetch tasks dispatched.
        """
        dispatched = 0

        # Dedup AND dispatch in same loop (not separated)
        async with self._seen_lock:
            for edge in edges:
                key = (edge.source_ioc, edge.target_ioc)
                if key in self._seen_edges:
                    continue  # Skip already-seen edge
                self._seen_edges.add(key)

                try:
                    self._prefetch_queue.put_nowait((edge, None))
                    dispatched += 1
                    self._stats.edges_received += 1
                except asyncio.QueueFull:
                    break  # Backpressure

        self._stats.prefetch_dispatched += dispatched
        return dispatched

    async def _prefetch_worker(self, worker_id: int) -> None:
        """Worker that processes prefetch tasks from queue."""
        logger.debug(f"SpeculativePrefetcher: worker-{worker_id} started")

        while True:
            try:
                edge, _ = await self._prefetch_queue.get()

                if edge is None:  # Poison pill
                    self._prefetch_queue.task_done()
                    logger.debug(f"SpeculativePrefetcher: worker-{worker_id} received poison")
                    return

                await self._execute_prefetch(edge)
                self._prefetch_queue.task_done()

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.warning(f"SpeculativePrefetcher: worker-{worker_id} error: {e}")

        logger.debug(f"SpeculativePrefetcher: worker-{worker_id} stopped")

    async def _execute_prefetch(self, edge: SpeculativeEdge) -> None:
        """Execute a single speculative prefetch."""
        try:
            if edge.target_type == "domain":
                # Speculatively prefetch DNS records for co-occurring domain
                if self._candidate_ledger is not None:
                    self._candidate_ledger.add_candidate(
                        candidate=edge.target_ioc,
                        source="speculative_cooccurrence",
                        family="PIVOT",
                        reason=f"co-occurred with {edge.source_ioc} "
                               f"({edge.confidence:.0%} confidence)",
                    )
            elif edge.target_type == "url":
                # Speculatively prefetch URL
                if self._fetch_coordinator is not None:
                    # Fire-and-forget prefetch
                    asyncio.create_task(
                        self._fetch_coordinator.prefetch_url(edge.target_ioc)  # type: ignore
                    )
            elif edge.target_type == "ip":
                # Speculatively prefetch IP info (passive DNS, etc.)
                if self._candidate_ledger is not None:
                    self._candidate_ledger.add_candidate(
                        candidate=edge.target_ioc,
                        source="speculative_cooccurrence",
                        family="PIVOT",
                        reason=f"IP co-occurred with {edge.source_ioc}",
                    )

            self._stats.prefetch_completed += 1

        except Exception as e:
            self._stats.prefetch_failed += 1
            logger.warning(f"SpeculativePrefetcher: prefetch failed for {edge.target_ioc}: {e}")

    def get_stats(self) -> PrefetcherStats:
        """Return prefetcher statistics."""
        return self._stats
