[package]
name = "hledac-hash"
version.workspace = true
edition.workspace = true

[lib]
name = "hledac_hash"
crate-type = ["cdylib", "rlib"]

[dependencies]
xxhash-rust.workspace = true
blake3.workspace = true
blake2.workspace = true
ahash.workspace = true
sha2.workspace = true
rayon.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
blake3 = { workspace = true, features = ["neon"] }
