# Stub for Vision (pyobjc-framework-Vision; Darwin-only)
# Minimal surface — only what hledac/tools/vision_analyzer.py uses.
from typing import Any

VNRequestRecognitionLevelAccurate: int
VNRequestRecognitionLevelFast: int

class VNImageRequestHandler:
    @classmethod
    def alloc(cls) -> VNImageRequestHandler: ...
    def initWithData_options_(self, data: Any, options: dict | None) -> VNImageRequestHandler: ...
    def initWithCGImage_options_(self, image: Any, options: dict | None) -> VNImageRequestHandler: ...
    def performRequests_error_(self, requests: list, error: Any) -> tuple[bool, Any]: ...

class VNRecognizeTextRequest:
    @classmethod
    def new(cls) -> VNRecognizeTextRequest: ...
    def setRecognitionLevel_(self, level: int) -> None: ...
    def setUsesLanguageCorrection_(self, b: bool) -> None: ...
    def setRecognitionLanguages_(self, langs: list[str]) -> None: ...
    def setMinimumTextHeight_(self, h: float) -> None: ...
    def setCustomWords_(self, words: list[str]) -> None: ...
    def results(self) -> list | None: ...

class VNDetectBarcodesRequest:
    @classmethod
    def new(cls) -> VNDetectBarcodesRequest: ...
    def setSymbologies_(self, syms: list) -> None: ...
    def results(self) -> list | None: ...

class VNDetectFaceRectanglesRequest:
    @classmethod
    def new(cls) -> VNDetectFaceRectanglesRequest: ...
    def results(self) -> list | None: ...

class VNGenerateImageFeaturePrintRequest:
    @classmethod
    def new(cls) -> VNGenerateImageFeaturePrintRequest: ...
    def setImageFeaturePrintObservation_(self, fp: Any) -> None: ...
    def results(self) -> list | None: ...

class VNImageBasedRequest:
    pass

class VNObservation:
    pass

class VNRectangleObservation(VNObservation):
    boundingBox: Any

class VNFeaturePrintObservation(VNObservation):
    data: Any
    elementType: int
    elementCount: int

class VNRecognizedTextObservation(VNObservation):
    def topCandidates_(self, max_n: int) -> list[Any]: ...
