# Stub for zstd (PyPI: zstd) — used in tools/zstd_compressor.py
# Minimal surface for compression/decompression in hot path.

class Error(Exception): ...

# Module-level functions
def compress(data: bytes, level: int = 3) -> bytes: ...
def decompress(data: bytes, max_output_size: int = 0) -> bytes: ...
def dumps(data: bytes, level: int = 3) -> bytes: ...
def loads(data: bytes, max_output_size: int = 0) -> bytes: ...
def check(data: bytes) -> int: ...
def verify(data: bytes) -> bool: ...
def version() -> int: ...
def ZSTD_version() -> str: ...
def ZSTD_version_number() -> int: ...
def ZSTD_version_compiled() -> str: ...
def ZSTD_version_loaded() -> str: ...
def ZSTD_compress(data: bytes, level: int = 0) -> bytes: ...
def ZSTD_uncompress(data: bytes) -> bytes: ...
def ZSTD_compress2(data: bytes, compression_level: int) -> bytes: ...
def ZSTD_compress_old(data: bytes, level: int) -> bytes: ...
def ZSTD_compress_real_mt(data: bytes, level: int, threads: int) -> bytes: ...
def ZSTD_check(data: bytes) -> int: ...
def ZSTD_default_compression_level() -> int: ...
def ZSTD_max_compression_level() -> int: ...
def ZSTD_min_compression_level() -> int: ...
def ZSTD_is_debug_enabled() -> bool: ...
def ZSTD_is_debug_error_enabled() -> bool: ...
def ZSTD_is_debug_info_enabled() -> bool: ...
def ZSTD_is_debug_notice_enabled() -> bool: ...
def ZSTD_legacy_support() -> int: ...
def ZSTD_with_asm() -> int: ...
def ZSTD_with_threads() -> int: ...
def ZSTD_threads_count() -> int: ...
def ZSTD_setCpuCoresCacheTTL(ttl: int) -> None: ...
def ZSTD_stopCpuCoresCache() -> None: ...
def ZSTD_external() -> int: ...
