# Stub for zstd (PyPI: zstd) — used in tools/zstd_compressor.py
# Minimal surface for compression/decompression in hot path.
#
# NOTE: The sergey-dryabzhinsky/python-zstd package (1.5.7.3) exposes ONLY
# module-level functions + Error. It has no class-based API.
# The class-based surface below mirrors the `zstandard` (python-zstandard,
# indresb) package, which `tools/zstd_compressor.py` actually imports via
# `import zstandard as zstd`. This stub provides class resolution through
# that alias for static type checking.

class Error(Exception): ...

# Module-level functions
def compress(data: bytes, level: int = 3) -> bytes: ...
def decompress(data: bytes, max_output_size: int = 0) -> bytes: ...
def dumps(data: bytes, level: int = 3) -> bytes: ...
def loads(data: bytes, max_output_size: int = 0) -> bytes: ...
def check(data: bytes) -> int: ...
def verify(data: bytes) -> bool: ...
def version() -> int: ...
def ZSTD_version() -> str: ...
def ZSTD_version_number() -> int: ...
def ZSTD_version_compiled() -> str: ...
def ZSTD_version_loaded() -> str: ...
def ZSTD_compress(data: bytes, level: int = 0) -> bytes: ...
def ZSTD_uncompress(data: bytes) -> bytes: ...
def ZSTD_compress2(data: bytes, compression_level: int) -> bytes: ...
def ZSTD_compress_old(data: bytes, level: int) -> bytes: ...
def ZSTD_compress_real_mt(data: bytes, level: int, threads: int) -> bytes: ...
def ZSTD_check(data: bytes) -> int: ...
def ZSTD_default_compression_level() -> int: ...
def ZSTD_max_compression_level() -> int: ...
def ZSTD_min_compression_level() -> int: ...
def ZSTD_is_debug_enabled() -> bool: ...
def ZSTD_is_debug_error_enabled() -> bool: ...
def ZSTD_is_debug_info_enabled() -> bool: ...
def ZSTD_is_debug_notice_enabled() -> bool: ...
def ZSTD_legacy_support() -> int: ...
def ZSTD_with_asm() -> int: ...
def ZSTD_with_threads() -> int: ...
def ZSTD_threads_count() -> int: ...
def ZSTD_setCpuCoresCacheTTL(ttl: int) -> None: ...
def ZSTD_stopCpuCoresCache() -> None: ...
def ZSTD_external() -> int: ...

# Class-based surface (mirrors `zstandard` 0.25.0, used via `as zstd` alias).

class ZstdCompressionDict:
    def __init__(self, data: bytes, dict_type: int = ...) -> None: ...
    def as_bytes(self) -> bytes: ...
    def dict_id(self) -> int: ...
    def precompute_compress(self, buffers: list[bytes], *args: object, **kwargs: object) -> list[object]: ...
    # Raw zstd dict data (used as `dict_data=` arg to ZstdCompressor/ZstdDecompressor).
    d: bytes
    k: int

class ZstdCompressor:
    def __init__(
        self,
        level: int = 3,
        dict_data: ZstdCompressionDict | None = None,
        compression_params: dict[str, int] | None = None,
        write_checksum: bool | None = None,
        write_content_size: bool | None = None,
        write_dict_id: bool | None = None,
        threads: int = 0,
    ) -> None: ...
    def compress(self, data: bytes) -> bytes: ...
    def compressobj(self, *args: object, **kwargs: object) -> object: ...
    def chunker(self, *args: object, **kwargs: object) -> object: ...
    def copy_stream(self, *args: object, **kwargs: object) -> object: ...
    def multi_compress_to_buffer(self, *args: object, **kwargs: object) -> list[bytes]: ...
    def read_to_iter(self, *args: object, **kwargs: object) -> object: ...
    def stream_reader(self, *args: object, **kwargs: object) -> object: ...
    def stream_writer(self, *args: object, **kwargs: object) -> object: ...
    def frame_progression(self) -> tuple[int, int, int]: ...
    def memory_size(self) -> int: ...

class ZstdDecompressor:
    def __init__(
        self,
        dict_data: ZstdCompressionDict | None = None,
        max_window_size: int = 0,
        format: int = 0,
    ) -> None: ...
    def decompress(self, data: bytes, max_output_size: int = 0) -> bytes: ...
    def decompressobj(self, *args: object, **kwargs: object) -> object: ...
    def copy_stream(self, *args: object, **kwargs: object) -> object: ...
    def decompress_content_dict_chain(self, *args: object, **kwargs: object) -> bytes: ...
    def multi_decompress_to_buffer(self, *args: object, **kwargs: object) -> list[bytes]: ...
    def read_to_iter(self, *args: object, **kwargs: object) -> object: ...
    def stream_reader(self, *args: object, **kwargs: object) -> object: ...
    def stream_writer(self, *args: object, **kwargs: object) -> object: ...
    def memory_size(self) -> int: ...

def train_dictionary(
    dict_size: int,
    samples: list[bytes],
    **kwargs: object,
) -> ZstdCompressionDict: ...
