// AUTO-GENERATED by tools/codegen_ioc_patterns.py — DO NOT EDIT.
// Source of truth: rust_extensions/src/ioc_patterns.rs
// Generated: 2026-07-14
// Hash: ca9dfa0098f0
// Version: v2

//! IOC pattern constants for Rust modules.
//! Single source of truth — patterns are shared between SIMD extractor and Python fallback.
//! DO NOT edit manually — edit ioc_patterns.rs and regenerate.

/// IPv4 pattern — ordered first for SIMD extractor's build_many index 0.
pub static IPV4_PAT: &str = r"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b";

/// Domain pattern — index 1 in build_many.
pub static DOMAIN_PAT: &str = r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}\b";

/// MD5 pattern — index 2 in build_many.
pub static MD5_PAT: &str = r"\b[a-fA-F0-9]{32}\b";

/// SHA1 pattern — index 3 in build_many.
pub static SHA1_PAT: &str = r"\b[a-fA-F0-9]{40}\b";

/// SHA256 pattern — index 4 in build_many.
pub static SHA256_PAT: &str = r"\b[a-fA-F0-9]{64}\b";

/// Email pattern — index 5 in build_many.
pub static EMAIL_PAT: &str = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b";

/// CVE pattern — index 6 in build_many (no trailing \b).
pub static CVE_PAT: &str = r"CVE-\d{4}-\d{4,}";

/// MAC address pattern — index 7 in build_many.
pub static MAC_PAT: &str = r"\b[0-9a-fA-F]{2}(?:[:\-][0-9a-fA-F]{2}){5}\b";

/// Bitcoin address pattern — index 8 in build_many.
pub static BTC_PAT: &str = r"\b(?:bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\b";

/// Ethereum address pattern — index 9 in build_many.
pub static ETH_PAT: &str = r"\b0x[a-fA-F0-9]{40}\b";

/// IPv6 pattern — handled separately from build_many (NFA size limit).
/// Not indexed in SIMD build_many; use IPV6_PAT in ioc_extract_simd.rs.
pub static IPV6_PAT: &str = r"\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b";
