# Stub for lancedb (LanceDB ANN vector store).
# LanceDB provides high-capacity vector search with IVF-PQ support.
# Lazy-imported at runtime when HLEDAC_VECTOR_BACKEND="lancedb".

from typing import Any
from collections.abc import Sequence

class LanceDBConnection:
    def open_table(self, name: str) -> LanceTable: ...
    def create_table(self, name: str, schema: Any, exist_ok: bool = False) -> LanceTable: ...
    def close(self) -> None: ...

class LanceTable:
    def search(self, query: list[float]) -> LanceSearchBuilder: ...
    def merge_insert(self, on: str) -> LanceMergeBuilder: ...
    def create_fts_index(self, col: str, replace: bool = False, **kwargs: Any) -> None: ...
    def list_indices(self) -> list[Any]: ...

class LanceSearchBuilder:
    def limit(self, n: int) -> LanceSearchBuilder: ...
    def to_arrow(self) -> Any: ...
    def to_list(self) -> list[dict[str, Any]]: ...

class LanceMergeBuilder:
    def on(self, on: str) -> LanceMergeBuilder: ...
    def execute(self, data: Any) -> None: ...

def connect(uri: str) -> LanceDBConnection: ...
