# Stub for sqlite-vec (zero-process ANN via SQLite virtual table).
# sqlite-vec provides vec0 virtual table for in-process ANN search.
# Lazy-imported at runtime when HLEDAC_VECTOR_BACKEND="sqlite-vec".

from typing import Any

class Connection:
    def execute(self, sql: str, params: list[Any] | tuple[Any, ...] | None = None) -> Connection: ...
    def executemany(self, sql: str, params: list[tuple[Any, ...]]) -> None: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...

def connect(path: str) -> Connection: ...
