# Type stubs for the `hledac_rust_extensions` PyO3 extension.
# Mirrors the runtime API surface consumed by `tests/test_hledac_core_rust.py`
# and other ty/mypy consumers. The actual symbols come from the compiled
# .so installed at runtime; this file is for static type checking only.
from typing import Any

class BloomFilter:
    def __init__(self, capacity: int, fp_rate: float) -> None: ...
    def add(self, item: bytes | str) -> None: ...
    def __contains__(self, item: bytes | str) -> bool: ...

class FastHasher:
    @staticmethod
    def hash(data: bytes) -> int: ...

class RollingHashEngine:
    def __init__(self, window_size: int) -> None: ...
    def update(self, byte: int) -> int: ...

class IntCounterLayoutRust:
    def __init__(self, keys: list[str]) -> None: ...
    def bump(self, key: str, amount: int = 1) -> None: ...
    def snapshot(self) -> dict[str, int]: ...

class IocDedupStore:
    def __init__(self) -> None: ...
    def add(self, value: str, ioc_type: str) -> bool: ...

def batch_dedup_urls(urls: list[str]) -> list[str]: ...
def fast_ioc_extract(text: str) -> list[dict[str, str]]: ...
def url_normalize(url: str) -> str: ...
def batch_content_hash(items: list[bytes]) -> list[int]: ...
def batch_content_hash_hex(items: list[bytes]) -> list[str]: ...
def content_hash_64(data: bytes) -> int: ...
def content_hash_hex(data: bytes) -> str: ...
def fingerprint(data: bytes) -> int: ...
def normalize(url: str) -> str: ...
def strip_tracking_params(url: str) -> str: ...
def compute_simhash(text: str) -> int: ...
def batch_compute_simhash(texts: list[str]) -> list[int]: ...
def find_near_duplicates(hashes: list[int], threshold: int) -> list[tuple[int, int]]: ...
def hamming_distance(a: int, b: int) -> int: ...
def is_near_duplicate(a: int, b: int, threshold: int) -> bool: ...
def bulk_bump_aggregate(keys: list[str], amounts: list[int]) -> dict[str, int]: ...
def bulk_snapshot_dict(store: Any) -> dict[str, int]: ...
def chain_hash_snapshot(store: Any) -> bytes: ...
