"""
Deprecated: mlx_memory re-exported from mlx_memory._core.
See hledac.universal.utils.mlx_memory package.
"""

import warnings as _warnings

_warnings.warn(
    "hledac.universal.utils.mlx_memory is deprecated; "
    "import from hledac.universal.utils.mlx_memory instead (F330-MLX-DUP-007)",
    DeprecationWarning,
    stacklevel=2,
)

from hledac.universal.utils.mlx_memory import (
from core import aclose
    MLX_AVAILABLE,
    init_mlx_buffers,
    configure_mlx_limits,
    get_mlx_active_memory_mb,
    get_mlx_peak_memory_mb,
    get_mlx_cache_memory_mb,
    get_mlx_memory_pressure,
    get_mlx_memory_metrics,
    format_mlx_memory_snapshot,
    clear_mlx_cache,
    clear_mlx_cache_debounced,
    set_cache_limit_with_debounce,
    mlx_cleanup_sync,
    mlx_cleanup_aggressive,
    metal_reclaim,
    safe_clear_metal_cache,
    get_dynamic_metal_cache_limit,
    get_metal_limits_status,
    safe_set_cache_limit,
    safe_get_cache_limit,
    get_metal_stream_context,
    get_mlx_model,
    evict_all,
    get_cache_stats,
    get_semaphore,
    MetalSlabPool,
    release_slab_pool,
    MLXPromptCache,
    MetalBufferPool,
    get_buffer_pool,
    init_metal_embedder_buffers,
    release_metal_embedder_buffers,
    SharedTensor,
    _MLX_CACHE_LIMIT,
    _MLX_WIRED_LIMIT,
)

__all__ = [
    "MLX_AVAILABLE",
    "init_mlx_buffers",
    "configure_mlx_limits",
    "get_mlx_active_memory_mb",
    "get_mlx_peak_memory_mb",
    "get_mlx_cache_memory_mb",
    "get_mlx_memory_pressure",
    "get_mlx_memory_metrics",
    "format_mlx_memory_snapshot",
    "clear_mlx_cache",
    "clear_mlx_cache_debounced",
    "set_cache_limit_with_debounce",
    "mlx_cleanup_sync",
    "mlx_cleanup_aggressive",
    "metal_reclaim",
    "safe_clear_metal_cache",
    "get_dynamic_metal_cache_limit",
    "get_metal_limits_status",
    "safe_set_cache_limit",
    "safe_get_cache_limit",
    "get_metal_stream_context",
    "get_mlx_model",
    "evict_all",
    "get_cache_stats",
    "get_semaphore",
    "MetalSlabPool",
    "release_slab_pool",
    "MLXPromptCache",
    "MetalBufferPool",
    "get_buffer_pool",
    "init_metal_embedder_buffers",
    "release_metal_embedder_buffers",
    "SharedTensor",
    "_MLX_CACHE_LIMIT",
    "_MLX_WIRED_LIMIT",
]
