"""
hledac_types/ — Re-export shim for project_types.py

ISSUE 7.2: Split preparation. All types are currently in project_types.py.
This package provides a future-proof import path for incremental migration.

Usage (current):
    from hledac.universal.project_types import ResearchMode, AgentMetrics, ...

Usage (after migration):
    from hledac.universal.types import ResearchMode, AgentMetrics, ...
"""

from hledac.universal.project_types import (
    # DTOs (msgspec.Struct)
    ActionResult,
    # Enums
    ActionResultType,
    ActionType,
    # Configs (msgspec.Struct)
    AgentManagerConfig,
    AgentMetrics,
    AgentState,
    AnalyzerResult,
    AnonymizationLevel,
    ArchiveSnapshot,
    BranchDecision,
    BrowserType,
    CanonicalGroundingHints,
    CaptchaSolution,
    CaptchaType,
    # Exceptions
    CircuitBreakerOpenError,
    CommunicationConfig,
    CommunicationPattern,
    ComplexityAnalysis,
    ContentSource,
    CoordinationConfig,
    DataLeakAlert,
    DecisionContext,
    DecisionRequest,
    DecisionResponse,
    DeepResearchConfig,
    DestructionResult,
    EventType,
    ExecutionContext,
    ExecutionRequest,
    ExecutionResult,
    ExplorationNode,
    ExplorationStrategy,
    ExportHandoff,
    GhostAction,
    GhostConfig,
    GhostMission,
    LeakSource,
    MemoryConfig,
    MemoryPressureError,
    MessagePriority,
    # UNIFIED-004: Micro-sprint types
    MicroSprintPlan,
    MicroSprintResult,
    ModelConfig,
    NeuromorphicEnergyReport,
    NeuronParameters,
    ObfuscationLevel,
    OfflineModeError,
    OperationType,
    OrchestratorError,
    OrchestratorState,
    PrivacyConfig,
    PrivacyEventCategory,
    PrivacyLevel,
    PrivacyStatus,
    ProcessingMetrics,
    ProcessingResult,
    ProcessingState,
    ProtocolType,
    ProviderRequest,
    ProviderResult,
    QueryComplexity,
    RateLimitExceeded,
    ReasoningMode,
    ResearchConfig,
    ResearchMode,
    ResearchPhase,
    ResearchResult,
    ReservoirConfig,
    RiskLevel,
    RunCorrelation,
    SecurityConfig,
    SecurityLevel,
    Severity,
    SNNConfig,
    SNNEncryptedContainer,
    SpikeData,
    StagnationError,
    STDPParams,
    StealthConfig,
    StealthSession,
    SubAgentResult,
    SubAgentType,
    SystemMetrics,
    SystemState,
    WipeStandard,
)

__all__ = [
    # Enums
    "ActionResultType",
    "ActionType",
    "AgentState",
    "AnonymizationLevel",
    "BrowserType",
    "CaptchaType",
    "CommunicationPattern",
    "ContentSource",
    "EventType",
    "ExplorationStrategy",
    "LeakSource",
    "MessagePriority",
    "OperationType",
    "PrivacyEventCategory",
    "PrivacyLevel",
    "ProcessingState",
    "ProtocolType",
    "ReasoningMode",
    "ResearchMode",
    "RiskLevel",
    "SecurityLevel",
    "Severity",
    "SubAgentType",
    "SystemState",
    "OrchestratorState",
    "QueryComplexity",
    "ResearchPhase",
    "ObfuscationLevel",
    "WipeStandard",
    # Exceptions
    "CircuitBreakerOpenError",
    "MemoryPressureError",
    "OfflineModeError",
    "OrchestratorError",
    "RateLimitExceeded",
    "StagnationError",
    # Configs
    "AgentManagerConfig",
    "CoordinationConfig",
    "CommunicationConfig",
    "DeepResearchConfig",
    "GhostConfig",
    "MemoryConfig",
    "ModelConfig",
    "PrivacyConfig",
    "ResearchConfig",
    "SecurityConfig",
    "SNNConfig",
    "StealthConfig",
    "STDPParams",
    "ReservoirConfig",
    # DTOs
    "ActionResult",
    "AnalyzerResult",
    "ArchiveSnapshot",
    "BranchDecision",
    "CanonicalGroundingHints",
    "DataLeakAlert",
    "DecisionContext",
    "DecisionRequest",
    "DecisionResponse",
    "DestructionResult",
    "ExportHandoff",
    "ExecutionContext",
    "ExecutionRequest",
    "ExecutionResult",
    "ExplorationNode",
    "GhostAction",
    "GhostMission",
    "NeuromorphicEnergyReport",
    "NeuronParameters",
    "ProcessingMetrics",
    "ProcessingResult",
    "ProviderRequest",
    "ProviderResult",
    "RunCorrelation",
    "SNNEncryptedContainer",
    "SpikeData",
    "StealthSession",
    "CaptchaSolution",
    "PrivacyStatus",
    "SubAgentResult",
    "ResearchResult",
    "SystemMetrics",
    "AgentMetrics",
    "ComplexityAnalysis",
    # UNIFIED-004: Micro-sprint types
    "MicroSprintPlan",
    "MicroSprintResult",
]
