#!/usr/bin/env python3
"""Codegen: Generate Python IOC patterns + docs from Rust source.

Single source of truth: rust_extensions/src/ioc_patterns.rs
This script generates:
  1. forensics/ioc_patterns_generated.py  — Python re.compile(...) blocks
  2. docs/ioc_types.md                   — Markdown reference table

Usage:
    python tools/codegen_ioc_patterns.py [--check] [--verbose]
    --check  : Exit 1 if any generated file is stale (CI gate)
    --verbose: Print diff on regenerate

Idempotent: running twice with same inputs produces identical outputs.
"""

from __future__ import annotations

import hashlib
import os
import re
import sys
from datetime import date
from pathlib import Path

# ─── Configuration ────────────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RUST_SOURCE = PROJECT_ROOT / "rust_extensions" / "src" / "ioc_patterns.rs"
PYTHON_OUT = PROJECT_ROOT / "forensics" / "ioc_patterns_generated.py"
DOCS_OUT = PROJECT_ROOT / "docs" / "ioc_types.md"
RUST_OUT = PROJECT_ROOT / "rust_extensions" / "src" / "ioc_patterns_generated.rs"
HASH_VERSION = "v2"  # Bump if regeneration logic changes

# ─── Parsing ──────────────────────────────────────────────────────────────────

_IOC_PATTERN_RE = re.compile(
    r'^pub static (?P<name>(?:IPV4|IPV6|DOMAIN|MD5|SHA1|SHA256|EMAIL|CVE|URL|HASH|MAC|BTC|ETH|'
    r'ENCODING_(?:BASE32|BASE64|HEX|HIGH_ENTROPY))_PAT): &str\s*=\s*$'
)

_PATTERN_VALUE_RE = re.compile(r'^\s+r"(.*)";\s*$', re.DOTALL)


def parse_rust_patterns(source: str) -> dict[str, str]:
    """Parse pub static *_PAT = r"..." lines from ioc_patterns.rs.

    Handles two layouts:
      1. Declaration and value on the same line:
             pub static IPV6_PAT: &str = r"...";
      2. Declaration on one line, value on the next (indented):
             pub static IPV4_PAT: &str =
                 r"...";

    Returns:
        dict[name -> pattern_string]
    """
    patterns: dict[str, str] = {}
    lines = source.splitlines()

    # Pattern for inline declaration + value on same line
    inline_pat = re.compile(
        r'^pub static (?P<name>\w+_PAT): &str = (?P<val>r"[^"]*");'
    )
    # Pattern for declaration-only line (value on next line).
    # The = is optional — some declarations end with "=" when value is on next line.
    decl_pat = re.compile(
        r'^pub static (?P<name>(?:IPV4|IPV6|DOMAIN|MD5|SHA1|SHA256|EMAIL|CVE|URL|HASH|'
        r'MAC|BTC|ETH|ENCODING_(?:BASE32|BASE64|HEX|HIGH_ENTROPY))_PAT): &str\s*=\s*$'
    )

    for i, line in enumerate(lines):
        # Try inline: "pub static NAME_PAT: &str = r"...";"
        im = inline_pat.match(line)
        if im:
            raw = im.group("val")
            patterns[im.group("name")] = raw[2:-1].replace('\\"', '"')
            continue

        # Try declaration-only line
        dm = decl_pat.match(line)
        if not dm:
            continue
        pat_name = dm.group("name")

        # Value is on the next non-blank/non-comment line.
        # Note: value_pat REQUIRES leading whitespace (spaces/tabs before r"..."),
        # so we check the stripped version only for blank/comment, not for matching.
        for j in range(i + 1, min(i + 5, len(lines))):
            raw_line = lines[j]
            stripped = raw_line.strip()
            if not stripped or stripped.startswith("//"):
                continue
            vm = _PATTERN_VALUE_RE.match(raw_line)
            if vm:
                patterns[pat_name] = vm.group(1).replace('\\"', '"')
                break

    return patterns


def _normalize_name(name: str) -> str:
    """Convert IPV4_PAT -> ipv4, ENCODING_BASE32_PAT -> encoding_base32."""
    return name.replace("_PAT", "").lower()


def _group_name(name: str) -> str:
    """Map static var name to IOC group name used in Python fallback."""
    return _normalize_name(name)


# ─── Python codegen ─────────────────────────────────────────────────────────────

# Only include actual IOC types (not encoding/diagnostic patterns).
# Encoding patterns (ENCODING_*) and generic HASH_PAT are used for
# DNS tunneling analysis but NOT for IOC extraction.
_IOC_ONLY_PATTERNS = frozenset([
    "IPV4_PAT", "IPV6_PAT", "DOMAIN_PAT",
    "MD5_PAT", "SHA1_PAT", "SHA256_PAT",
    "EMAIL_PAT", "CVE_PAT",
    "MAC_PAT", "BTC_PAT", "ETH_PAT",
])

_PYTHON_HEADER = """\
# AUTO-GENERATED by tools/codegen_ioc_patterns.py — DO NOT EDIT.
# Source of truth: rust_extensions/src/ioc_patterns.rs
# Generated: {generated_date}
# Hash: {source_hash}
# Version: {hash_version}

from __future__ import annotations

import re as _re

# Hash validators — mirrors forensics/ioc_extractor.py
_HASH_VALIDATORS = {{
    "md5":    lambda v: len(v) == 32 and all(c in "0123456789abcdefABCDEF" for c in v),
    "sha1":   lambda v: len(v) == 40 and all(c in "0123456789abcdefABCDEF" for c in v),
    "sha256": lambda v: len(v) == 64 and all(c in "0123456789abcdefABCDEF" for c in v),
}}

# Tracking params for URL normalization
_TRACKING_PARAMS = {{
    "utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content",
    "fbclid", "gclid", "mc_cid", "mc_eid", "ref", "ref_src", "ref_url",
}}

# ─── IOC Patterns ───────────────────────────────────────────────────────────────
# Single source of truth — patterns mirror rust_extensions/src/ioc_patterns.rs
# DO NOT edit manually — edit ioc_patterns.rs and regenerate.

_IOC_PATTERNS: list[tuple[str, str]] = [
"""

_PYTHON_TAIL = """\

_IOC_TYPE_NAMES: list[str] = [name for name, _ in _IOC_PATTERNS]

# Single combined regex — one finditer pass, no rescanning.
_IOC_COMBINED = _re.compile(
    "|".join(f"(?P<{name}>{pattern})" for name, pattern in _IOC_PATTERNS)
)
"""


def generate_python(patterns: dict[str, str], source_hash: str) -> str:
    """Generate the Python patterns module."""
    lines = [_PYTHON_HEADER.format(
        generated_date=date.today().isoformat(),
        source_hash=source_hash[:12],
        hash_version=HASH_VERSION,
    )]

    for name, pattern in patterns.items():
        if name not in _IOC_ONLY_PATTERNS:
            continue
        group = _group_name(name)
        # Escape triple quotes and format
        safe_pattern = pattern.replace('"', '\\"')
        lines.append(f'    ("{group}", r"{safe_pattern}"),  # {name}')

    lines.append("]")
    lines.append("")
    lines.append(_PYTHON_TAIL)

    return "\n".join(lines)


# ─── Rust codegen ──────────────────────────────────────────────────────────────

# Only actual IOC types for SIMD extractor (excludes URL/HASH/ENCODING_*).
# Order MUST match pattern_to_ioc_type index in ioc_extract_simd.rs:
#   0=IPv4, 1=Domain, 2=MD5, 3=SHA1, 4=SHA256, 5=Email, 6=CVE, 7=MAC, 8=BTC, 9=ETH
_SIMD_PATTERN_ORDER = [
    "IPV4_PAT", "DOMAIN_PAT",
    "MD5_PAT", "SHA1_PAT", "SHA256_PAT",
    "EMAIL_PAT", "CVE_PAT",
    "MAC_PAT", "BTC_PAT", "ETH_PAT",
]

_RUST_HEADER = """\
// AUTO-GENERATED by tools/codegen_ioc_patterns.py — DO NOT EDIT.
// Source of truth: rust_extensions/src/ioc_patterns.rs
// Generated: {generated_date}
// Hash: {source_hash}
// Version: {hash_version}

//! IOC pattern constants for Rust modules.
//! Single source of truth — patterns are shared between SIMD extractor and Python fallback.
//! DO NOT edit manually — edit ioc_patterns.rs and regenerate.

/// IPv4 pattern — ordered first for SIMD extractor's build_many index 0.
pub static IPV4_PAT: &str = {ipv4_val};

/// Domain pattern — index 1 in build_many.
pub static DOMAIN_PAT: &str = {domain_val};

/// MD5 pattern — index 2 in build_many.
pub static MD5_PAT: &str = {md5_val};

/// SHA1 pattern — index 3 in build_many.
pub static SHA1_PAT: &str = {sha1_val};

/// SHA256 pattern — index 4 in build_many.
pub static SHA256_PAT: &str = {sha256_val};

/// Email pattern — index 5 in build_many.
pub static EMAIL_PAT: &str = {email_val};

/// CVE pattern — index 6 in build_many (no trailing \\b).
pub static CVE_PAT: &str = {cve_val};

/// MAC address pattern — index 7 in build_many.
pub static MAC_PAT: &str = {mac_val};

/// Bitcoin address pattern — index 8 in build_many.
pub static BTC_PAT: &str = {btc_val};

/// Ethereum address pattern — index 9 in build_many.
pub static ETH_PAT: &str = {eth_val};

/// IPv6 pattern — handled separately from build_many (NFA size limit).
/// Not indexed in SIMD build_many; use IPV6_PAT in ioc_extract_simd.rs.
pub static IPV6_PAT: &str = {ipv6_val};
"""


def _rust_quote(s: str) -> str:
    """Quote a Rust string literal for inclusion in &str = r"...";.

    Handles backslashes, quotes, and special chars.
    """
    # For raw strings, only the quote character needs escaping (not backslashes).
    # We use r"..." syntax, so double quotes must be escaped.
    escaped = s.replace('"', '\\"')
    return f'r"{escaped}"'


def generate_rust(patterns: dict[str, str], source_hash: str) -> str:
    """Generate Rust pattern constants module."""
    def get(name: str) -> str:
        raw = patterns.get(name, "")
        return _rust_quote(raw)

    return _RUST_HEADER.format(
        generated_date=date.today().isoformat(),
        source_hash=source_hash[:12],
        hash_version=HASH_VERSION,
        ipv4_val=get("IPV4_PAT"),
        domain_val=get("DOMAIN_PAT"),
        md5_val=get("MD5_PAT"),
        sha1_val=get("SHA1_PAT"),
        sha256_val=get("SHA256_PAT"),
        email_val=get("EMAIL_PAT"),
        cve_val=get("CVE_PAT"),
        mac_val=get("MAC_PAT"),
        btc_val=get("BTC_PAT"),
        eth_val=get("ETH_PAT"),
        ipv6_val=get("IPV6_PAT"),
    )


# ─── Docs codegen ───────────────────────────────────────────────────────────────

_DOCS_HEADER = """\
# IOC Types Reference

> **Generated from:** `rust_extensions/src/ioc_patterns.rs`
> **Regenerate:** `python tools/codegen_ioc_patterns.py`
> **Last update:** {generated_date}

## Quick Reference

| Type | Group | RFC / Standard | Notes |
|------|-------|----------------|-------|
"""

_DOCS_ROW = "| `{type}` | `{group}` | {rfc} | {notes} |"


_RFC_MAP = {
    "ipv4": "RFC 791",
    "ipv6": "RFC 4291",
    "domain": "RFC 1035",
    "email": "RFC 5321",
    "url": "RFC 3986",
    "md5": "—",
    "sha1": "—",
    "sha256": "—",
    "cve": "CVE Format",
    "mac": "IEEE 802",
    "btc": "Bitcoin Base58/Bech32",
    "eth": "Ethereum Yellow Paper",
    "encoding_base32": "RFC 4648",
    "encoding_base64": "RFC 4648",
    "encoding_hex": "—",
    "encoding_high_entropy": "—",
}


def generate_docs(patterns: dict[str, str], source_hash: str) -> str:
    """Generate the docs/ioc_types.md table."""
    lines = [
        _DOCS_HEADER.format(generated_date=date.today().isoformat()),
        _DOCS_ROW.format(
            type="ipv4", group="ipv4", rfc="RFC 791", notes="0-255 octets, word boundaries"
        ),
    ]

    for name, pattern in patterns.items():
        if name == "IPV4_PAT":
            continue
        group = _group_name(name)
        rfc = _RFC_MAP.get(group, "—")

        # Shorten pattern for display (first 60 chars)
        short = pattern[:60] + "..." if len(pattern) > 60 else pattern

        if group.startswith("encoding_"):
            notes = f"encoding pattern: {short}"
        else:
            notes = short

        lines.append(_DOCS_ROW.format(type=group, group=group, rfc=rfc, notes=notes))

    lines.append("")
    lines.append("## Pattern Sources")
    lines.append("")
    lines.append(f"- **Rust source:** `rust_extensions/src/ioc_patterns.rs` (hash: `{source_hash[:12]}`)")
    lines.append("- **Generated Python:** `forensics/ioc_patterns_generated.py`")
    lines.append("- **Generated Rust:** `rust_extensions/src/ioc_patterns_generated.rs`")
    lines.append("")

    return "\n".join(lines)


# ─── Main ──────────────────────────────────────────────────────────────────────

def file_hash(path: Path) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()


def run(check: bool = False) -> int:
    """Run codegen.

    Returns:
        0 if generated files are up-to-date (or regenerated).
        1 if --check and files are stale.
    """
    if not RUST_SOURCE.exists():
        print(f"ERROR: Source not found: {RUST_SOURCE}", file=sys.stderr)
        return 2

    source = RUST_SOURCE.read_text()
    source_hash = hashlib.sha1(source.encode()).hexdigest()
    patterns = parse_rust_patterns(source)

    if not patterns:
        print("ERROR: No patterns parsed from ioc_patterns.rs", file=sys.stderr)
        return 2

    print(f"Parsed {len(patterns)} patterns from {RUST_SOURCE}")

    # ── Python ──────────────────────────────────────────────────────────────────
    py_content = generate_python(patterns, source_hash)
    py_changed = True
    if PYTHON_OUT.exists():
        existing = PYTHON_OUT.read_text()
        py_changed = (existing != py_content)
        if not py_changed:
            print(f"  [skip] {PYTHON_OUT} — unchanged")
        else:
            PYTHON_OUT.write_text(py_content)
            print(f"  [write] {PYTHON_OUT}")
    else:
        PYTHON_OUT.parent.mkdir(parents=True, exist_ok=True)
        PYTHON_OUT.write_text(py_content)
        print(f"  [write] {PYTHON_OUT} (new)")

    # ── Rust ────────────────────────────────────────────────────────────────────
    rust_content = generate_rust(patterns, source_hash)
    rust_changed = True
    if RUST_OUT.exists():
        existing = RUST_OUT.read_text()
        rust_changed = (existing != rust_content)
        if not rust_changed:
            print(f"  [skip] {RUST_OUT} — unchanged")
        else:
            RUST_OUT.write_text(rust_content)
            print(f"  [write] {RUST_OUT}")
    else:
        RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
        RUST_OUT.write_text(rust_content)
        print(f"  [write] {RUST_OUT} (new)")

    # ── Docs ───────────────────────────────────────────────────────────────────
    docs_content = generate_docs(patterns, source_hash)
    docs_changed = True
    if DOCS_OUT.exists():
        existing = DOCS_OUT.read_text()
        docs_changed = (existing != docs_content)
        if not docs_changed:
            print(f"  [skip] {DOCS_OUT} — unchanged")
        else:
            DOCS_OUT.write_text(docs_content)
            print(f"  [write] {DOCS_OUT}")
    else:
        DOCS_OUT.parent.mkdir(parents=True, exist_ok=True)
        DOCS_OUT.write_text(docs_content)
        print(f"  [write] {DOCS_OUT} (new)")

    # ── Check mode ─────────────────────────────────────────────────────────────
    if check and (py_changed or docs_changed or rust_changed):
        print("ERROR: Generated files are stale (run without --check to regenerate)", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Codegen IOC patterns from Rust source")
    parser.add_argument("--check", action="store_true", help="Exit 1 if files are stale")
    args = parser.parse_args()

    sys.exit(run(check=args.check))
